CREATE DATABASE OLA;
USE OLA;
CREATE TABLE DRIVER1
(
DR_ID INT  PRIMARY KEY,
DR_NAME VARCHAR(20),
DR_PICKUP VARCHAR(33),
DR_DROFOFF VARCHAR(20),
DR_DATE DATE ,
DR_FARE INT
);
 
 CREATE TABLE PASSENGER1
 (
 PA_ID INT PRIMARY KEY,
 PA_NAME VARCHAR(20),
 PA_VAHCLE ENUM ("AVAILABLE","CANCELLED","RESERVED"),
 FOREIGN KEY (PA_DR) REFERENCES DRIVER1(DR_ID)
 );
SELECT * FROM PASSENGER1
INNER JOIN DRIVER1
ON DRIVER1.DR_ID = PASSENGER1.PA_ID;
  
SELECT * FROM passenger1
RIGHT JOIN driver1
ON driver1.DR_ID = passenger1.pa_id;

  

 
 
 